env:
  browser: true
  es2021: true
  node: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns: ['*.test.js']
rules:
  no-prototype-builtins: off
  no-unused-vars:
  - error
  -
    argsIgnorePattern: ^_
    varsIgnorePattern: ^_
  no-constant-condition: off
  getter-return: off
  no-misleading-character-class: off