env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns: ['*.test.js']
rules:
  no-prototype-builtins: off
  no-unused-vars:
  - error
  - argsIgnorePattern: ^_
