install:
  - npm install --dev
script:
  - npm install -g .
  - npm run build
  - cd docs
  - canopy build --for-static-assets
  - cd ..
after_success:
  - bash script/code_deploy.sh
  - bash script/docs_deploy.sh
env:
  global:
    - secure: "wjhMDS7LHlJbw882I6eNN6UnIi4UsmlWuqNdGPbzShJAi7Q9nlxakkRXI+WkmmLZc4QF+1dyaT0HXr/v29G/vsjk36N1/CokJSQM6eNKt5CMW2wbCoTdgqCOP7cw1Cg1EHfkrq/YwCeqemfnpLfd1fx/LEab6Jhlp5IpQGMtrQYC+OyMIw3yrkEEseIhilKvrND0iXCLDiBwPySiRHN+i8NLtQGzOnn/LiUj915025IH4lMj/NeRZ6r6d89hBWudaXsrNJZZnwV4AbJEKBK3RQc6N32bHldnw/R7lrIfK+le90CWAFTCBHSvxr2FweSSn5QOz2+kUlXzwx0fhAWpHEyqPX5Bj1cBhePg9Y3mS1Tb/IDLiHsydNZlyxwsfOLgop85RACB9XYFHa8aTAbk70k6HJC650Wi/0LhtrGz9s7/tIV/giu3aYZPJQi70EZcvQa5KcFCr0ZzUQGJAotwrPye8w1K3Hx6vO1IvvwgSiT6NzSec2Q9WKRhEYz76+5HhMMXTWBK4atkYZQiZ1HFpAVYYhThTScEP9690IJgMJ3sju7kyk2F1dY1DI6HLSaoAvVUq5ZUYEQRJYJmQWUHNuvDONusjAaTP7fzsh8vGwJveC6hgg2VuZtBBcqqB9TmJ1diR1QSiCg/m/yGnyTSiCr1CqDZmpaukzmihGKHyXA="
