env:
  node: true
  commonjs: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
ignorePatterns: ['*.test.js']
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-prototype-builtins: off
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_

