name: Build Playground
on:
  push:
    branches:
      - main

jobs:
  tests:
     uses: canopy-js/canopy-js/.github/workflows/tests.yml@main
  build:
    needs: tests
    if: github.ref == 'refs/heads/main' && needs.tests.outputs.done == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14

    - run: npm install
    - run: npm run build-prod
    - name: Restore Playwright browsers from cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - run: |
        npx serve -s dist/playground -l 5000 &
        for i in {1..10}; do curl -sSf http://localhost:5000 && break; sleep 1; done
        node playground/test-console.js
      shell: bash

    - run: |
        set -ex
        rev=$(git rev-parse --short HEAD)

        git config --global user.email "canopyjs@gmail.com"
        git config --global user.name "Canopy JS"

        git checkout -b playground || git checkout playground
        git fetch origin playground
        git reset --hard origin/playground || true

        # move dist/playground to . and remove other files from .
        shopt -s extglob
        rm -rf -- !(dist)
        mv dist/playground/* .
        rm -rf dist

        cat ./google_analytics_tag.txt >> index.html

        git add -A
        git commit -m "Playground built at ${rev}" --allow-empty
        git push -u origin playground --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
