name: Build Playground
on:
  push:
    branches:
      - main
jobs:
  tests:
    uses: canopy-js/canopy-js/.github/workflows/tests.yml@main
  build:
    needs: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && needs.tests.result == 'success'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npm run build-prod
      - run: |
          mkdir ../playground-deploy
          cp dist/playground/playground.js ../playground-deploy/
          cp dist/playground/playground.js.map ../playground-deploy/
          cp dist/playground/index.html ../playground-deploy/
          cp dist/playground/favicon.ico ../playground-deploy/
          cp dist/playground/logo.png ../playground-deploy/
          cp dist/playground/google_analytics_tag.txt ../playground-deploy/
      - run: |
          set -ex
          rev=$(git rev-parse --short HEAD)

          git config --global user.email "canopyjs@gmail.com"
          git config --global user.name "Canopy JS"

          git checkout -b playground || git checkout playground

          git fetch origin playground
          git reset --hard origin/playground || true

          rm -rf *
          cp -r ../playground-deploy/* .

          cat ./google_analytics_tag.txt >> index.html

          git add -A
          git commit -m "Playground built at ${rev}" --allow-empty
          git push -u origin playground --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}