name: Build Prod Code
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm install
    - run: npm run build-prod
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -ex
        rev=$(git rev-parse --short HEAD)

        git fetch origin
        git reset origin/build

        npm run build-prod

        git add -A

        git config --global user.email "canopyjs@gmail.com"
        git config --global user.name "Canopy JS"

        git commit -m "Code built at ${rev}" --allow-empty
        git push -q origin HEAD:build

