name: Build Prod Code
on:
  push:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Build canopy assets
      run: npm run build-prod
    - name: Install canopy
      run: npm install -g .
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run regular tests
      run: npm run jest
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm install
    - run: npm run build-prod
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -ex
        rev=$(git rev-parse --short HEAD)

        rm -rf .git
        git init

        git remote add origin "https://canopy-js:$GITHUB_TOKEN@github.com/canopy-js/canopy-js.git"
        git fetch origin
        git reset origin/build

        npm run build-prod

        git add -A

        git config --global user.email "canopyjs@gmail.com"
        git config --global user.name "Canopy JS"

        git commit -m "Code built at ${rev}" --allow-empty
        git push -q origin HEAD:build

