name: Build Prod Code
on:
  push:
    branches:
      - main
jobs:
  tests:
     uses: canopy-js/canopy-js/.github/workflows/tests.yml@main
  build:
    needs: tests
    if: github.ref == 'refs/heads/main' && needs.tests.outputs.done == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm run build-prod
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -ex
        rev=$(git rev-parse --short HEAD)

        rm -rf .git
        git init

        git remote add origin "https://canopy-js:$GITHUB_TOKEN@github.com/canopy-js/canopy-js.git"
        git fetch origin
        git reset origin/build

        npm run build-prod

        git add -A

        git config --global user.email "canopyjs@gmail.com"
        git config --global user.name "Canopy JS"

        git commit -m "Code built at ${rev}" --allow-empty
        git push -q origin HEAD:build

